@startuml
set namespaceSeparator ::

class "quicko::controllers::auth_controller.dart::AuthController" {
  -FirebaseAuth _auth
  -FirebaseFirestore _firestore
  -FirebaseStorage _storage
  -dynamic _uploadProfileImageToStorage()
  +dynamic pickProfileImage()
  +dynamic signUpUsers()
  +dynamic loginUsers()
}

"quicko::controllers::auth_controller.dart::AuthController" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"quicko::controllers::auth_controller.dart::AuthController" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"quicko::controllers::auth_controller.dart::AuthController" o-- "firebase_storage::firebase_storage.dart::FirebaseStorage"

class "quicko::main.dart::InitialScreen" {
  +State<InitialScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::main.dart::InitialScreen"

class "quicko::main.dart::_InitialScreenState" {
  +void initState()
  +void checkOnboardStatus()
  +void showOnboardScreen()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::main.dart::_InitialScreenState"

class "quicko::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::main.dart::MyApp"

class "quicko::models::cart_attributes.dart::CartAttributes" {
  +String productName
  +String productId
  +List<dynamic> imageUrl
  +int quantity
  +int productQuantity
  +double price
  +String vendorId
  +void increase()
  +void decrease()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "quicko::models::cart_attributes.dart::CartAttributes"

class "quicko::onboarding_screen.dart::OnboardingScreen" {
  +State<OnboardingScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::onboarding_screen.dart::OnboardingScreen"

class "quicko::onboarding_screen.dart::_OnboardingScreenState" {
  -PageController _pageController
  -int _pageIndex
  +void initState()
  +void dispose()
  +Widget build()
}

"quicko::onboarding_screen.dart::_OnboardingScreenState" o-- "flutter::src::widgets::page_view.dart::PageController"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::onboarding_screen.dart::_OnboardingScreenState"

class "quicko::onboarding_screen.dart::DotIndicator" {
  +bool isActive
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::onboarding_screen.dart::DotIndicator"

class "quicko::onboarding_screen.dart::Onboard" {
  +String image
  +String title
  +String description
}

class "quicko::onboarding_screen.dart::OnBoardContent" {
  +String image
  +String title
  +String description
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::onboarding_screen.dart::OnBoardContent"

class "quicko::provider::cart_provider.dart::CartProvider" {
  -Map<String, CartAttributes> _cartItems
  +Map<String, CartAttributes> getCartItems
  +double totalPrice
  +void addProductToCart()
  +void increment()
  +void decreament()
  +void removeItem()
  +void removeAllItem()
  +bool isVendorIdSame()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "quicko::provider::cart_provider.dart::CartProvider"

class "quicko::provider::product_provider.dart::ProductProvider" {
  +Map<String, dynamic> productData
  +dynamic getFormData()
  +dynamic clearData()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "quicko::provider::product_provider.dart::ProductProvider"

class "quicko::size_config.dart::SizeConfig" {
  {static} -MediaQueryData _mediaQueryData
  {static} +double screenWidth
  {static} +double screenHeight
  {static} +double? defaultSize
  {static} +Orientation? orientation
  +void init()
}

"quicko::size_config.dart::SizeConfig" o-- "flutter::src::widgets::media_query.dart::MediaQueryData"
"quicko::size_config.dart::SizeConfig" o-- "flutter::src::widgets::media_query.dart::Orientation"

class "quicko::splash_screen.dart::SplashScreen" {
  +State<SplashScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::splash_screen.dart::SplashScreen"

class "quicko::splash_screen.dart::_SplashScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::splash_screen.dart::_SplashScreenState"

class "quicko::vendor::controllers::vendor_register_controller.dart::VendorController" {
  -FirebaseStorage _storage
  -FirebaseAuth _auth
  -FirebaseFirestore _firestore
  -dynamic _uploadVendorImageToStorage()
  +dynamic pickStoreImage()
  +dynamic registorVendor()
}

"quicko::vendor::controllers::vendor_register_controller.dart::VendorController" o-- "firebase_storage::firebase_storage.dart::FirebaseStorage"
"quicko::vendor::controllers::vendor_register_controller.dart::VendorController" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"quicko::vendor::controllers::vendor_register_controller.dart::VendorController" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"

class "quicko::vendor::models::vender_user_models.dart::VendorUserModel" {
  +bool? approved
  +String? businessName
  +String? cityValue
  +String? countryValue
  +String? stateValue
  +String? email
  +String? phone
  +String? storeImage
  +String? vendorId
  +Map<String, Object?> toJson()
}

class "quicko::vendor::views::auth::vendor_auth.dart::VendorAuthScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::auth::vendor_auth.dart::VendorAuthScreen"

class "quicko::vendor::views::auth::vendor_registor.dart::VendorRegisterScreen" {
  +State<VendorRegisterScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::auth::vendor_registor.dart::VendorRegisterScreen"

class "quicko::vendor::views::auth::vendor_registor.dart::_VendorRegisterScreenState" {
  -GlobalKey<FormState> _formKey
  -FirebaseAuth _auth
  +String countryValue
  +String cityValue
  +String stateValue
  +String businessName
  +String email
  +String phone
  -Uint8List? _image
  -VendorController _vendorController
  +dynamic selectGalleryImage()
  +dynamic selectCameraImage()
  -dynamic _saveVendorDetail()
  +Widget build()
}

"quicko::vendor::views::auth::vendor_registor.dart::_VendorRegisterScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"quicko::vendor::views::auth::vendor_registor.dart::_VendorRegisterScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"quicko::vendor::views::auth::vendor_registor.dart::_VendorRegisterScreenState" o-- "dart::typed_data::Uint8List"
"quicko::vendor::views::auth::vendor_registor.dart::_VendorRegisterScreenState" o-- "quicko::vendor::controllers::vendor_register_controller.dart::VendorController"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::auth::vendor_registor.dart::_VendorRegisterScreenState"

class "quicko::vendor::views::screens::edit_product_screen.dart::EditProductScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::screens::edit_product_screen.dart::EditProductScreen"

class "quicko::vendor::views::screens::edit_product_tabs::published_tab.dart::PublishedTab" {
  -FirebaseFirestore _firestore
  +Widget build()
}

"quicko::vendor::views::screens::edit_product_tabs::published_tab.dart::PublishedTab" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::screens::edit_product_tabs::published_tab.dart::PublishedTab"

class "quicko::vendor::views::screens::edit_product_tabs::unpublished_tab.dart::UnpublishedTab" {
  -FirebaseFirestore _firestore
  +Widget build()
}

"quicko::vendor::views::screens::edit_product_tabs::unpublished_tab.dart::UnpublishedTab" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::screens::edit_product_tabs::unpublished_tab.dart::UnpublishedTab"

class "quicko::vendor::views::screens::landing_screen.dart::LandingScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::screens::landing_screen.dart::LandingScreen"

class "quicko::vendor::views::screens::main_vendor_screen.dart::MainVendorScreen" {
  +State<MainVendorScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::screens::main_vendor_screen.dart::MainVendorScreen"

class "quicko::vendor::views::screens::main_vendor_screen.dart::_MainVendorScreenState" {
  -int _pageIndex
  -List<Widget> _pages
  -void _selectPage()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::screens::main_vendor_screen.dart::_MainVendorScreenState"

class "quicko::vendor::views::screens::scan_screen.dart::ScanScreen" {
  +_ScanScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::screens::scan_screen.dart::ScanScreen"

class "quicko::vendor::views::screens::scan_screen.dart::_ScanScreenState" {
  +GlobalKey<State<StatefulWidget>> qrKey
  +Barcode? result
  +QRViewController? controller
  -FirebaseAuth _auth
  +Widget build()
  -void _onQRViewCreated()
  +void dispose()
}

"quicko::vendor::views::screens::scan_screen.dart::_ScanScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<State<StatefulWidget>>"
"quicko::vendor::views::screens::scan_screen.dart::_ScanScreenState" o-- "qr_code_scanner::src::types::barcode.dart::Barcode"
"quicko::vendor::views::screens::scan_screen.dart::_ScanScreenState" o-- "qr_code_scanner::src::qr_code_scanner.dart::QRViewController"
"quicko::vendor::views::screens::scan_screen.dart::_ScanScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::screens::scan_screen.dart::_ScanScreenState"

class "quicko::vendor::views::screens::upload_screen.dart::UploadScreen" {
  -GlobalKey<FormState> _formKey
  -FirebaseFirestore _firestore
  +Widget build()
}

"quicko::vendor::views::screens::upload_screen.dart::UploadScreen" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"quicko::vendor::views::screens::upload_screen.dart::UploadScreen" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::screens::upload_screen.dart::UploadScreen"

class "quicko::vendor::views::screens::upload_tab_screens::general_screen.dart::GeneralScreen" {
  +State<GeneralScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::screens::upload_tab_screens::general_screen.dart::GeneralScreen"

class "quicko::vendor::views::screens::upload_tab_screens::general_screen.dart::_GeneralScreenState" {
  -FirebaseFirestore _firestore
  -List<String> _categoryList
  +bool wantKeepAlive
  -dynamic _getCategories()
  +void initState()
  +Widget build()
}

"quicko::vendor::views::screens::upload_tab_screens::general_screen.dart::_GeneralScreenState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::screens::upload_tab_screens::general_screen.dart::_GeneralScreenState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "quicko::vendor::views::screens::upload_tab_screens::general_screen.dart::_GeneralScreenState"

class "quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::ImagesScreen" {
  +State<ImagesScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::ImagesScreen"

class "quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::_ImagesScreenState" {
  +ImagePicker picker
  -FirebaseStorage _storage
  -List<File> _image
  -List<String> _imageUrlList
  +bool wantKeepAlive
  +dynamic chooseImage()
  +Widget build()
}

"quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::_ImagesScreenState" o-- "image_picker::image_picker.dart::ImagePicker"
"quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::_ImagesScreenState" o-- "firebase_storage::firebase_storage.dart::FirebaseStorage"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::_ImagesScreenState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "quicko::vendor::views::screens::upload_tab_screens::%C4%B1mages_screen.dart::_ImagesScreenState"

class "quicko::vendor::views::screens::vendorProductDetail::vendor_product_detail_screen.dart::VendorProductDetailScreen" {
  +dynamic productData
  +State<VendorProductDetailScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::screens::vendorProductDetail::vendor_product_detail_screen.dart::VendorProductDetailScreen"

class "quicko::vendor::views::screens::vendorProductDetail::vendor_product_detail_screen.dart::_VendorProductDetailScreenState" {
  -FirebaseFirestore _firestore
  -TextEditingController _productNameController
  -TextEditingController _quantityController
  -TextEditingController _productPriceController
  -TextEditingController _productDescriptionController
  -TextEditingController _categoryNameController
  +double? productPrice
  +int? productQuantity
  +void initState()
  +Widget build()
}

"quicko::vendor::views::screens::vendorProductDetail::vendor_product_detail_screen.dart::_VendorProductDetailScreenState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"quicko::vendor::views::screens::vendorProductDetail::vendor_product_detail_screen.dart::_VendorProductDetailScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::screens::vendorProductDetail::vendor_product_detail_screen.dart::_VendorProductDetailScreenState"

class "quicko::vendor::views::screens::vendor_logout_screen.dart::VendorLogoutScreen" {
  -FirebaseAuth _auth
  +Widget build()
}

"quicko::vendor::views::screens::vendor_logout_screen.dart::VendorLogoutScreen" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::vendor::views::screens::vendor_logout_screen.dart::VendorLogoutScreen"

class "quicko::vendor::views::screens::vendor_order_screen.dart::VendorOrderScreen" {
  +_VendorOrderScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::vendor::views::screens::vendor_order_screen.dart::VendorOrderScreen"

class "quicko::vendor::views::screens::vendor_order_screen.dart::_VendorOrderScreenState" {
  -FirebaseAuth _auth
  -FirebaseFirestore _firestore
  +Widget build()
}

"quicko::vendor::views::screens::vendor_order_screen.dart::_VendorOrderScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"quicko::vendor::views::screens::vendor_order_screen.dart::_VendorOrderScreenState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::vendor::views::screens::vendor_order_screen.dart::_VendorOrderScreenState"

class "quicko::views::customers::auth::login_screen.dart::LoginScreen" {
  +State<LoginScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::auth::login_screen.dart::LoginScreen"

class "quicko::views::customers::auth::login_screen.dart::_LoginScreenState" {
  -GlobalKey<FormState> _formKey
  -AuthController _authController
  +String email
  +String password
  -bool _isLoading
  -dynamic _loginUsers()
  +Widget build()
  +dynamic checkVendorEnrollment()
  +void initState()
  +void handleLogin()
}

"quicko::views::customers::auth::login_screen.dart::_LoginScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"quicko::views::customers::auth::login_screen.dart::_LoginScreenState" o-- "quicko::controllers::auth_controller.dart::AuthController"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::auth::login_screen.dart::_LoginScreenState"

class "quicko::views::customers::auth::register_screen.dart::CustomerRegisterScreen" {
  +State<CustomerRegisterScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::auth::register_screen.dart::CustomerRegisterScreen"

class "quicko::views::customers::auth::register_screen.dart::_CustomerRegisterScreenState" {
  -AuthController _authController
  -GlobalKey<FormState> _formKey
  +String email
  +String fullName
  +String phoneNumber
  +String password
  -bool _isLoading
  -Uint8List? _image
  -dynamic _singUpUsers()
  +dynamic selectGalleryImage()
  +dynamic selectCameraImage()
  +Widget build()
}

"quicko::views::customers::auth::register_screen.dart::_CustomerRegisterScreenState" o-- "quicko::controllers::auth_controller.dart::AuthController"
"quicko::views::customers::auth::register_screen.dart::_CustomerRegisterScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"quicko::views::customers::auth::register_screen.dart::_CustomerRegisterScreenState" o-- "dart::typed_data::Uint8List"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::auth::register_screen.dart::_CustomerRegisterScreenState"

class "quicko::views::customers::main_screen.dart::MainScreen" {
  +State<MainScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::main_screen.dart::MainScreen"

class "quicko::views::customers::main_screen.dart::_MainScreenState" {
  -int _pageIndex
  -List<Widget> _pages
  -PageController _pageController
  +void initState()
  +void dispose()
  -void _selectPage()
  +Widget build()
}

"quicko::views::customers::main_screen.dart::_MainScreenState" o-- "flutter::src::widgets::page_view.dart::PageController"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::main_screen.dart::_MainScreenState"

class "quicko::views::customers::nav_screens::account_screen.dart::AccountsScreen" {
  -FirebaseAuth _auth
  +Widget build()
}

"quicko::views::customers::nav_screens::account_screen.dart::AccountsScreen" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::account_screen.dart::AccountsScreen"

class "quicko::views::customers::nav_screens::cart_screen.dart::CartScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::cart_screen.dart::CartScreen"

class "quicko::views::customers::nav_screens::components::body.dart::Body" {
  +_BodyState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::components::body.dart::Body"

class "quicko::views::customers::nav_screens::components::body.dart::_BodyState" {
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::components::body.dart::_BodyState"

class "quicko::views::customers::nav_screens::components::cart_card.dart::CartCard" {
  +Cart cart
  +String generateQrData()
  +dynamic saveQrDataToFirestore()
  +Widget build()
}

"quicko::views::customers::nav_screens::components::cart_card.dart::CartCard" o-- "quicko::views::customers::nav_screens::models::Cart.dart::Cart"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::components::cart_card.dart::CartCard"

class "quicko::views::customers::nav_screens::components::check_out.dart::CheckoutCard" {
  +State<CheckoutCard> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::components::check_out.dart::CheckoutCard"

class "quicko::views::customers::nav_screens::components::check_out.dart::_CheckoutCardState" {
  +bool isPickedUp
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::components::check_out.dart::_CheckoutCardState"

class "quicko::views::customers::nav_screens::components::default_button.dart::DefaultButton" {
  +String? text
  +Function? press
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::components::default_button.dart::DefaultButton"

class "quicko::views::customers::nav_screens::home_screen.dart::HomeScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::home_screen.dart::HomeScreen"

class "quicko::views::customers::nav_screens::models::Cart.dart::Cart" {
  +Product product
  +int numOfItem
}

"quicko::views::customers::nav_screens::models::Cart.dart::Cart" o-- "quicko::views::customers::nav_screens::models::Product.dart::Product"

class "quicko::views::customers::nav_screens::models::Product.dart::Product" {
  +int id
  +String title
  +String description
  +List<String> images
  +List<Color> colors
  +double rating
  +double price
  +bool isFavourite
  +bool isPopular
}

class "quicko::views::customers::nav_screens::payment::generateQR_screen.dart::QRGeneratorScreen" {
  +_QRGeneratorScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::payment::generateQR_screen.dart::QRGeneratorScreen"

class "quicko::views::customers::nav_screens::payment::generateQR_screen.dart::_QRGeneratorScreenState" {
  +String qrData
  +void initState()
  +dynamic fetchLastOrder()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::payment::generateQR_screen.dart::_QRGeneratorScreenState"

class "quicko::views::customers::nav_screens::payment::payment_screen.dart::PaymentScreen" {
  +_PaymentScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::payment::payment_screen.dart::PaymentScreen"

class "quicko::views::customers::nav_screens::payment::payment_screen.dart::_PaymentScreenState" {
  -String? _selectedMethod
  +Widget build()
  +Widget content()
  +Widget paymentMethod()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::payment::payment_screen.dart::_PaymentScreenState"

class "quicko::views::customers::nav_screens::search_screen.dart::SearchScreen" {
  +State<SearchScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::search_screen.dart::SearchScreen"

class "quicko::views::customers::nav_screens::search_screen.dart::_SearchScreenState" {
  -String _searchedValue
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::search_screen.dart::_SearchScreenState"

class "quicko::views::customers::nav_screens::store_screen.dart::StoreScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::store_screen.dart::StoreScreen"

class "quicko::views::customers::nav_screens::widgets::banner_widget.dart::BannerWidget" {
  +State<BannerWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::widgets::banner_widget.dart::BannerWidget"

class "quicko::views::customers::nav_screens::widgets::banner_widget.dart::_BannerWidgetState" {
  -FirebaseFirestore _firestore
  -List<dynamic> _bannerImage
  +dynamic getBanners()
  +void initState()
  +Widget build()
}

"quicko::views::customers::nav_screens::widgets::banner_widget.dart::_BannerWidgetState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::widgets::banner_widget.dart::_BannerWidgetState"

class "quicko::views::customers::nav_screens::widgets::category_text.dart::CategoryText" {
  +State<CategoryText> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::widgets::category_text.dart::CategoryText"

class "quicko::views::customers::nav_screens::widgets::category_text.dart::_CategoryTextState" {
  -String? _selectedCategory
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::widgets::category_text.dart::_CategoryTextState"

class "quicko::views::customers::nav_screens::widgets::home_products.dart::HomeProductWidget" {
  +String categoryName
  +_HomeProductWidgetState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::widgets::home_products.dart::HomeProductWidget"

class "quicko::views::customers::nav_screens::widgets::home_products.dart::_HomeProductWidgetState" {
  +int initialDisplayCount
  +int displayCount
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::widgets::home_products.dart::_HomeProductWidgetState"

class "quicko::views::customers::nav_screens::widgets::main_products_widget.dart::MainProductWidget" {
  +_MainProductWidgetState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::widgets::main_products_widget.dart::MainProductWidget"

class "quicko::views::customers::nav_screens::widgets::main_products_widget.dart::_MainProductWidgetState" {
  -Stream<QuerySnapshot<Object?>> _productsStream
  -int _productCount
  +void initState()
  +Widget build()
}

"quicko::views::customers::nav_screens::widgets::main_products_widget.dart::_MainProductWidgetState" o-- "dart::async::Stream<QuerySnapshot<Object>>"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::widgets::main_products_widget.dart::_MainProductWidgetState"

class "quicko::views::customers::nav_screens::widgets::search_input_widget.dart::SearchInputWidget" {
  +State<SearchInputWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::widgets::search_input_widget.dart::SearchInputWidget"

class "quicko::views::customers::nav_screens::widgets::search_input_widget.dart::_SearchInputWidgetState" {
  +dynamic searchDocumentList
  +String productNameText
  +dynamic initSearching()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::widgets::search_input_widget.dart::_SearchInputWidgetState"

class "quicko::views::customers::nav_screens::widgets::stores_widget.dart::StoreText" {
  -Stream<QuerySnapshot<Object?>> _storeStream
  +Widget build()
}

"quicko::views::customers::nav_screens::widgets::stores_widget.dart::StoreText" o-- "dart::async::Stream<QuerySnapshot<Object>>"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::nav_screens::widgets::stores_widget.dart::StoreText"

class "quicko::views::customers::nav_screens::widgets::welcome_text_widget.dart::WelcomeText" {
  +_WelcomeTextState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::nav_screens::widgets::welcome_text_widget.dart::WelcomeText"

class "quicko::views::customers::nav_screens::widgets::welcome_text_widget.dart::_WelcomeTextState" {
  +int itemCount
  +Widget build()
  +void updateItemCount()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::nav_screens::widgets::welcome_text_widget.dart::_WelcomeTextState"

class "quicko::views::customers::productDetail::product_detail_screen.dart::ProductDetailScreen" {
  +dynamic productData
  +State<ProductDetailScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::customers::productDetail::product_detail_screen.dart::ProductDetailScreen"

class "quicko::views::customers::productDetail::product_detail_screen.dart::_ProductDetailScreenState" {
  -int _imageIndex
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::customers::productDetail::product_detail_screen.dart::_ProductDetailScreenState"

class "quicko::views::customers::productDetail::store_detail.dart::StoreDetailScreen" {
  +dynamic storeData
  +Widget build()
  +String capitalizeFirstLetter()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "quicko::views::customers::productDetail::store_detail.dart::StoreDetailScreen"

class "quicko::views::inner_screens::edit_profile.dart::EditProfileScreen" {
  +dynamic userData
  +State<EditProfileScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "quicko::views::inner_screens::edit_profile.dart::EditProfileScreen"

class "quicko::views::inner_screens::edit_profile.dart::_EditProfileScreenState" {
  -FirebaseFirestore _firestore
  -TextEditingController _fullNameController
  -TextEditingController _emailController
  -TextEditingController _phoneController
  +String? address
  +void initState()
  +Widget build()
}

"quicko::views::inner_screens::edit_profile.dart::_EditProfileScreenState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"quicko::views::inner_screens::edit_profile.dart::_EditProfileScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "quicko::views::inner_screens::edit_profile.dart::_EditProfileScreenState"


@enduml